name: movie-recommender
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - pandas
      - matplotlib
      - seaborn
      - joblib
      - scikit-surprise
